export const orderStatuses = [
  { label: 'Abandoned', value: 'ABANDONED' },
  { label: 'Pending', value: 'PENDING' },
  { label: 'Accepted', value: 'ACCEPTED' },
  { label: 'Ready To Pick Up', value: 'READY_TO_PICK_UP' },
  { label: 'Searching For Driver', value: 'SEARCHING_FOR_DRIVER' },
  { label: 'Driver Accepted', value: 'DRIVER_ACCEPTED' },
  { label: 'Driver On The Way', value: 'DRIVER_ON_THE_WAY' },
  { label: 'Driver Arrived', value: 'DRIVER_ARRIVED' },
  { label: 'Picked Up', value: 'PICKED_UP' },
  { label: 'On The Way to Customer', value: 'ON_THE_WAY_TO_CUSTOMER' },
  { label: 'Arrived At Customer', value: 'ARRIVED_AT_CUSTOMER' },
  { label: 'Failed', value: 'FAILED' },
  { label: 'Cancelled', value: 'CANCELLED' },
  { label: 'Refunded', value: 'REFUNDED' },
  { label: 'Partially Refunded', value: 'PARTIALLY_REFUNDED' },
  { label: 'Delivered', value: 'DELIVERED' },
  { label: 'Rejected', value: 'REJECTED' },
];
