name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting  #step 1
        env: 
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

      - name: install ssh pass  #step 2
        run: |
          sudo apt-get install -y sshpass

      - name: login to VM #step 3
        run: |
          
          # sshpass -p "welcome@12345" ssh welcomeuser@20.253.250.188
          sshpass -p "welcome@12345" ssh -o StrictHostKeyChecking=no welcomeuser@20.253.250.188
        

    
  
