name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code  #step 1 : checkout code
        uses: actions/checkout@v4
        # with:
        #   repository: 'Developer-Personal/invoice-crm'
        #   token: ${{ secrets.SOURCE_REPO_PAT }}



      - name: cd to the folder for test   #step 2 : see the content for testing only
        run: |
          echo "direcoty is : $(pwd)
          echo -e "contents are:- \n$(ls -la)"
