name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      #step 1 : checkout code
      - name: checkout the code 
        uses: actions/checkout@v4

      #step 2 : see the content for testing only
      - name: see the content for testing only 
        run: |
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"

      #step 3 : change env in client
      - name: change env in client
        run: |
          echo "VITE_API_BASE_URL = http://welcome-app1.azurewebsites.net" > client/.env
          echo -e "the env in client is: \n$(cat client/.env)"
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"

      #step 4 node envioronment setup
      - name: Setup Node.js environment   
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      #step 5 : build the app
      - name: build the app
        run: |
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"
          cd client
          npm install
          npm run build
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"
          echo -e "the env in client is: \n$(cat .env)"
          cd ..
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"
          cp -r client/dist server
          cd server
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"


      #step 6 : copy to artifact
      - name: copy to artifact and zip 
        run: |
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"
          mkdir artifact
          cp -r server/. artifact
          cd artifact
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"
          zip ../release.zip ./* -r
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"
          cd ..
          echo -e "contents in directory $(pwd) are:- \n$(ls -la)"

      #step 7 : upload artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip 

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app
    environment:
      name: 'Production'
      url: ${{ steps.deploy-on-webapp.outputs.webapp-url }}

    steps:
      #step 8 : download artifact
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      #step 9 : unzip artifact
      - name: unzip artifact
        run: |
          unzip release.zip

      #step 10 : Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-on-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: welcome-app1
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .


