name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      #step 1 : checkout code
      - name: checkout the code 
        uses: actions/checkout@v4

      #step 2 : see the content for testing only
      - name: see the content for testing only 
        run: |
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"

      #step 3 : change env in client
      - name: change env in client
        run: |
          echo "VITE_API_BASE_URL = http://adeel12-hvash4dvd5hcaec6.centralus-01.azurewebsites.net" > client/.env
          echo -e "the env in client is: \n$(cat client/.env)"
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"

      #step 4 node envioronment setup
      - name: Setup Node.js environment   
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      #step 5 : build the app
      - name: build the app
        run: |
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"
          cd client
          npm install
          npm run build
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"
          echo -e "the env in client is: \n$(cat .env)"
          cd ..
          echo "current direcoty is : $(pwd)"
          cp -r client/dist server
          cd server
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"


      #step 6 : copy to artifact
      - name: copy to artifact
        run: |
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"
          mkdir artifact
          cp -r server/. artifact
          echo "current direcoty is : $(pwd)"
          echo -e "contents are:- \n$(ls -la)"

