name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code  #step 1 : checkout code
        uses: actions/checkout@v4
        with:
          repository: 'Developer-Personal/invoice-crm'
          token: ${{ secrets.SOURCE_REPO_PAT }}



      - name: cd to the folder   #step 2 : see the content for testing only
        run: |
          ls -la

      - name: Setup Node.js environment   #step 3 node envioronment setup
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: cd to the folder   #step 4 : npm run build in clien folder
        run: |
          cd client
          npm install
          npm run build

      - name: cd to the folder   #step 5 : see the content for build
        run: |
          cd client
          ls -la

