name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code  #step 1
        uses: actions/checkout@v4
        with:
          repository: 'Developer-Personal/invoice-crm'
          token: ${{ secrets.SOURCE_REPO_PAT }}



      - name: cd to the folder   #step 2
        run: |
          ls -la

      # - name: login to VM #step 3
      #   run: |

        

    
  
