name: GitHub Actions Demo
on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env: 
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: login to VM
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "welcome@12345" ssh welcomeuser@20.253.250.188
        

    
  
